# Generated by Django 4.2.6 on 2023-10-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('arquivo', models.ImageField(blank=True, upload_to='upload/')),
                ('mensagem', models.CharField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
