# Generated by Django 4.2.6 on 2023-10-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
