# Generated by Django 4.2.6 on 2023-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_pedidos_options_alter_pedidos_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ['criacao'], 'verbose_name': 'Pedidos recebidos'},
        ),
        migrations.AddField(
            model_name='pedidos',
            name='anotacoes',
            field=models.CharField(blank=True, help_text='Insira as anotacoes da cotacao', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='conclusao',
            field=models.DateField(blank=True, help_text='Insira a data de conclusao, o mesmo da entrega do produto.', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cpf_envio',
            field=models.PositiveBigIntegerField(help_text='Insira o CPF do recebedor do despacho', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cpf_pagamento',
            field=models.PositiveBigIntegerField(help_text='Insira o CPF do pagador.', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='despacho',
            field=models.DateField(blank=True, help_text='Insira a data de despacho do produto.', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='endereco',
            field=models.CharField(blank=True, help_text='Insira o endereco para despacho', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='envio_orcamento',
            field=models.DateField(blank=True, help_text='Insira a data do envio do orcamento.', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pagamento',
            field=models.DateField(blank=True, help_text='Insira a data do pagamento.', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='prazo',
            field=models.DateField(blank=True, help_text='Insira o prazo para o envio do produto.', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_frete',
            field=models.FloatField(help_text='Insira o valor do frete cotado.', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_produto',
            field=models.FloatField(help_text='Insira o valor do produto cotado.', null=True),
        ),
    ]
