# Generated by Django 4.2.6 on 2023-10-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_pedidos_anotacoes_alter_pedidos_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cpf_envio',
            field=models.PositiveBigIntegerField(blank=True, help_text='Insira o CPF do recebedor do despacho', null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='valor_frete',
            field=models.FloatField(blank=True, help_text='Insira o valor do frete cotado.', null=True),
        ),
    ]
